### ISSUE TITLE
Search Function for existing entries

### ISSUE THREAD

**Issue by pooberry** [mhowe21/SmartSearch#13]
If we are planning on throwing this to the success team we will want them to be able to search and modify their existing entries as easily as possible. The search parameter that the app uses to search for entries will be the best to show where the new entry shows on the list.

siteadmin.instructure.com/accounts/search?search_term=

**Comment by mhowe21** [comment]
Search functionality beta added in 0.2.1.1 Currently flushing out other behaviors of that section.
